development:
  ACTIONMAILER_USERNAME:        'contacto@marcadorexacto.com'
  ACTIONMAILER_PASSWORD:        'Marcador5196'
  MAILGUN_API_KEY:              'key-66069eabbb0ae7a03301f6a0b372fcc8'
  MAILGUN_DOMAIN:               'mg.marcadorexacto.com'
  APIFOOTBALL_API_KEY:          '6d914f02442fddb9880c20715853f4a3e1b94582b01a6ef532b2aec2937180b3'
  GOOGLE_OMNIAUTH_APP_ID:       '329359827768-h79cvvqf47b33oh9rl3856hqr02dorak.apps.googleusercontent.com'
  GOOGLE_OMNIAUTH_APP_SECRET:   'tWxhEDHQSIO4Zo_vtRXxssoG'
  DATABASE_USERNAME:            'futbol'
  DATABASE_PASSWORD:            'futbol'
  FACEBOOK_OMNIAUTH_APP_ID:     '137806993456965'
  FACEBOOK_OMNIAUTH_APP_SECRET: 'a5ac975506692b9aa75dd114624d285c'
